apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: release-then-test-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-cel-expression: '"RELEASE_THEN_TEST_TRIGGER".pathChanged()'
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineRef:
    resolver: cluster
    params:
      - { name: kind, value: pipeline }
      - { name: name, value: build }
      - { name: namespace, value: platform-catalog }
  params:
    - { name: git-url, value: "{{ repo_url }}" }
    - { name: git-revision, value: "{{ revision }}" }
    - { name: image-repo, value: "ghcr.io/jfillman/cicd-flow-test-app" }
    - { name: app-namespace, value: "app-cicd-flow-test-app-cicd" }
    - { name: app-name, value: "cicd-flow-test-app" }
    - { name: app-type, value: "app" }

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
  taskRunTemplate:
    serviceAccountName: pipeline-runner
  timeouts:
    pipeline: "1h"
